apiVersion: v1
kind: ServiceAccount
metadata:
  name: anatomy-feedback-api
  namespace: anatomy-feedback
  labels:
    app: anatomy-feedback-api
  annotations:
    # After terraform apply, set to: module/output api_irsa_role_arn
    # eks.amazonaws.com/role-arn: arn:aws:iam::423687459077:role/anatomy-feedback-api-api-irsa
    eks.amazonaws.com/role-arn: arn:aws:iam::423687459077:role/anatomy-feedback-api-api-irsa
